config/routes.rb
Docket::Application.routes.draw do
	get "docket" => "docket#index"

	resources :memberships
	resources :exams
	resources :assignments

	resources :classrooms do
		member do
			get "join"
			get "leave"
		end
	end

	resources :courses
	resources :teachers
	resources :sessions

	resources :users do
		member do
			get "activity"
		end
		collection do
			get "activity" => "users#index_activities"
		end
	end

	resources :events do
		member do
			get "join"
			get "leave"
		end
	end

	get "sessions/new"
	get "log_in" => "sessions#new", :as => "log_in"
	get "log_out" => "sessions#destroy", :as => "log_out"

	root "docket#index"

	# Example of regular route:
	#   get "products/:id" => "catalog#view"

	# Example of named route that can be invoked with purchase_url(id: product.id)
	#   get "products/:id/purchase" => "catalog#purchase", as: :purchase

	# Example resource route (maps HTTP verbs to controller actions automatically):
	#   resources :products

	# Example resource route with options:
	#   resources :products dob
	#     member do
	#       get "short"
	#       post "toggle"
	#     end
	#
	#     collection do
	#       get "sold"
	#     end
	#   end

	# Example resource route with sub-resources:
	#   resources :products do
	#     resources :comments, :sales
	#     resource :seller
	#   end

	# Example resource route with more complex sub-resources:
	#   resources :products do
	#     resources :comments
	#     resources :sales do
	#       get "recent", on: :collection
	#     end
	#   end

	# Example resource route with concerns:
	#   concern :toggleable do
	#     post "toggle"
	#   end
	#   resources :posts, concerns: :toggleable
	#   resources :photos, concerns: :toggleable

	# Example resource route within a namespace:
	#   namespace :admin do
	#     # Directs /admin/products/* to Admin::ProductsController
	#     # (app/controllers/admin/products_controller.rb)
	#     resources :products
	#   end
end

app/models/event.rb
class Event < ActiveRecord::Base
	include PublicActivity::Model
	tracked owner: -> (controller, model) { controller && controller.current_user }

	has_many :attendances
	has_many :users, :through => :attendances

	def global?
		self.global
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	load_and_authorize_resource
	before_action :set_event, only: [:show, :edit, :update, :destroy]

	# GET /events
	# GET /events.json
	def index
		@events = Event.all
	end

	# GET /events/1
	# GET /events/1.json
	def show
	end

	# GET /events/new
	def new
		@event = Event.new
	end

	# GET /events/1/edit
	def edit
	end

	# POST /events
	# POST /events.json
	def create
		@event = Event.new(event_params)

		respond_to do |format|
			if @event.save
				format.html { redirect_to @event, notice: "Event was successfully created." }
				format.json { render action: "show", status: :created, location: @event }
			else
				format.html { render action: "new" }
				format.json { render json: @event.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /events/1
	# PATCH/PUT /events/1.json
	def update
		respond_to do |format|
			if @event.update(event_params)
				format.html { redirect_to @event, notice: "Event was successfully updated." }
				format.json { head :no_content }
			else
				format.html { render action: "edit" }
				format.json { render json: @event.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /events/1
	# DELETE /events/1.json
	def destroy
		@event.destroy
		respond_to do |format|
			format.html { redirect_to events_url }
			format.json { head :no_content }
		end
	end

	# GET /events/1/join
	# Copied from classroom controller
	def join
		@event = Event.find(params[:id])

		params[:user_id] = current_user.id unless admin? && params[:user_id]

		@attendance = Attendance.new
		@attendance.event_id = @event.id
		@attendance.user_id = params[:user_id]
		if @attendance.save
			redirect_to @event, notice: "Joined!"
		else
			redirect_to root_path, alert: "WTF did you just try to do."
		end
	end

	# GET /events/1/leave
	def leave
		@event = Event.find(params[:id])

		params[:user_id] = current_user.id unless admin? && params[:user_id]

		@attendance = Attendance.where("user_id = ? AND event_id = ?", params[:user_id], @event.id).first
		if @attendance.destroy
			redirect_to @event, notice: "Left!"
		else
			redirect_to root_path, alert: "WTF did you just try to do."
		end
	end


	private
	# Use callbacks to share common setup or constraints between actions.
	def set_event
		@event = Event.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def event_params
		params.require(:event).permit(:name, :description, :date, :global)
	end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for @event, :html => { :class => "form-horizontal" } do |f| %>
	<% if @event.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

			<ul>
				<% @event.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="form-group">
		<%= f.label :name, :class => "col-sm-4 control-label" %>
		<div class="col-sm-8">
			<%= f.text_field :name, :class => "form-control" %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :description, :class => "col-sm-4 control-label" %>
		<div class="col-sm-8">
			<%= f.text_area :description, :class => "form-control" %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :date, :class => "col-sm-4 control-label" %>
		<div class="col-sm-8">
			<%= f.datetime_select :date, :class => "form-control" %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :global, :class => "col-sm-4 control-label" %>
		<div class="col-sm-1">
			<%= f.check_box :global, :class => "form-control" %>
		</div>
	</div>

	<div class="form-group">
		<div class="col-sm-offset-4 col-sm-8">
			<%= f.submit class: "btn btn-success" %>
		</div>
	</div>
<% end %>

app/views/events/edit.html.erb
<div class="page-header">
	<h1>Editing event</h1>
</div>

<%= render 'form' %>

<div class="btn-group">
	<%= link_to 'Show', @event, class: "btn btn-primary" %>
	<%= link_to 'All Events', events_path, class: "btn btn-default" %>
</div>

app/views/events/index.html.erb
<div class="page-header">
	<h1>Listing events</h1>
</div>

<table class="table table-striped">
	<thead>
		<tr>
			<th>Name</th>
			<th>Date</th>
			<th>Actions</th>
		</tr>
	</thead>

	<tbody>
		<% @events.each do |event| %>
			<tr>
				<td><%= link_to event.name, event %></td>
				<td><%= event.date %></td>
				<td>
					<div class="btn-group btn-group-xs">
						<%= link_to 'Edit', edit_event_path(event), class: "btn btn-default btn-xs" %>
						<%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %>
					</div>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path, :class => "btn btn-success" %>

app/views/events/new.html.erb
<div class="page-header">
	<h1>New event</h1>
</div>

<%= render 'form' %>

<%= link_to 'All Events', events_path, class: "btn btn-default" %>

app/views/events/show.html.erb
<div class="page-header">
	<h1><%= @event.name %></h1>
</div>

<p>
	<%= @event.date %>
</p>

<p>
	<%= @event.description %>
</p>

<p>
	<% if @event.global? %>
		This event is global (and can therefore not be joined or left).
	<% else %>
		This event is not global.
	<% end %>
</p>


<div class="btn-group">
	<% if !@event.global? %>
	<% if @event.users.include? current_user %>
		<%= link_to "Leave", leave_event_path(@event), class: "btn btn-danger" %>
	<% else %>
		<%= link_to "Join", join_event_path(@event), class: "btn btn-success" %>
	<% end %>
	<% end %>

	<%= link_to 'Edit', edit_event_path(@event), class: "btn btn-primary" %>
	<%= link_to 'All Events', events_path, class: "btn btn-default" %>
</div>