config/routes.rb
Docket::Application.routes.draw do
	get "docket" => "docket#index"

	resources :memberships
	resources :exams
	resources :assignments

	resources :classrooms do
		member do
			get "join"
			get "leave"
		end
	end

	resources :courses
	resources :teachers
	resources :sessions

	resources :users do
		member do
			get "activity"
		end
		collection do
			get "activity" => "users#index_activities"
		end
	end

	resources :events do
		member do
			get "join"
			get "leave"
		end
	end

	get "sessions/new"
	get "log_in" => "sessions#new", :as => "log_in"
	get "log_out" => "sessions#destroy", :as => "log_out"

	root "docket#index"

	# Example of regular route:
	#   get "products/:id" => "catalog#view"

	# Example of named route that can be invoked with purchase_url(id: product.id)
	#   get "products/:id/purchase" => "catalog#purchase", as: :purchase

	# Example resource route (maps HTTP verbs to controller actions automatically):
	#   resources :products

	# Example resource route with options:
	#   resources :products dob
	#     member do
	#       get "short"
	#       post "toggle"
	#     end
	#
	#     collection do
	#       get "sold"
	#     end
	#   end

	# Example resource route with sub-resources:
	#   resources :products do
	#     resources :comments, :sales
	#     resource :seller
	#   end

	# Example resource route with more complex sub-resources:
	#   resources :products do
	#     resources :comments
	#     resources :sales do
	#       get "recent", on: :collection
	#     end
	#   end

	# Example resource route with concerns:
	#   concern :toggleable do
	#     post "toggle"
	#   end
	#   resources :posts, concerns: :toggleable
	#   resources :photos, concerns: :toggleable

	# Example resource route within a namespace:
	#   namespace :admin do
	#     # Directs /admin/products/* to Admin::ProductsController
	#     # (app/controllers/admin/products_controller.rb)
	#     resources :products
	#   end
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
	include PublicActivity::Model
	tracked owner: -> (controller, model) { controller && controller.current_user }

	validates :name, presence: true
	validates :email, format: { with: /\A[\w\-\.]+\@[\w\-\.]+\z/ }

	def first_name
		name.split(" ").first
	end

	def last_name
		name.split(" ").last
	end

	has_many :classrooms
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
	load_and_authorize_resource
	before_action :set_teacher, only: [:show, :edit, :update, :destroy]

	# GET /teachers
	# GET /teachers.json
	def index
		if params[:q]
			@teachers = Teacher.where("LOWER(name) LIKE LOWER(?)", "%" + params[:q] + "%").sort_by(&:last_name)
		else
			@teachers = Teacher.all.sort_by(&:last_name)
		end
		respond_to do |format|
			format.html
			format.json { render json: @teachers.map { |c| c.name } }
		end
	end

	# GET /teachers/1
	# GET /teachers/1.json
	def show
	end

	# GET /teachers/new
	def new
		@teacher = Teacher.new
	end

	# GET /teachers/1/edit
	def edit
	end

	# POST /teachers
	# POST /teachers.json
	def create
		@teacher = Teacher.new(teacher_params)

		respond_to do |format|
			if @teacher.save
				format.html { redirect_to @teacher, notice: "Teacher was successfully created." }
				format.json { render action: "show", status: :created, location: @teacher }
			else
				format.html { render action: "new" }
				format.json { render json: @teacher.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /teachers/1
	# PATCH/PUT /teachers/1.json
	def update
		respond_to do |format|
			if @teacher.update(teacher_params)
				format.html { redirect_to @teacher, notice: "Teacher was successfully updated." }
				format.json { head :no_content }
			else
				format.html { render action: "edit" }
				format.json { render json: @teacher.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /teachers/1
	# DELETE /teachers/1.json
	def destroy
		@teacher.destroy
		respond_to do |format|
			format.html { redirect_to teachers_url }
			format.json { head :no_content }
		end
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_teacher
		@teacher = Teacher.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def teacher_params
		params.require(:teacher).permit(:name, :email)
	end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_for @teacher, :html => { :class => "form-horizontal" } do |f| %>
	<% if @teacher.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

			<ul>
				<% @teacher.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="form-group">
		<%= f.label :name, :class => "col-sm-4 control-label" %>
		<div class="col-sm-8">
			<%= f.text_field :name, :class => "form-control" %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :email, :class => "col-sm-4 control-label" %>
		<div class="col-sm-8">
			<%= f.text_field :email, :class => "form-control" %>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-offset-4 col-sm-8">
			<%= f.submit class: "btn btn-success" %>
		</div>
	</div>
<% end %>

app/views/teachers/edit.html.erb
<div class="page-header">
	<h1>Editing teacher</h1>
</div>

<%= render 'form' %>

<div class="btn-group">
	<%= link_to 'Show', @teacher, class: "btn btn-primary" %>
	<%= link_to 'All Teachers', teachers_path, class: "btn btn-default" %>
</div>

app/views/teachers/index.html.erb
<div class="page-header">
	<h1>Listing teachers</h1>
</div>

<table class="table table-striped">
	<thead>
		<tr>
			<th>Name</th>
			<th>Email</th>
			<th>Actions</th>
		</tr>
	</thead>

	<tbody>
		<% @teachers.each do |teacher| %>
			<tr>
				<td><%= link_to teacher.name, teacher %></td>
				<td><%= mail_to teacher.email %></td>
				<td>
					<div class="btn-group btn-group-xs">
						<%= link_to "Edit", edit_teacher_path(teacher), class: "btn btn-default btn-xs" %>
						<%= link_to "Remove", teacher, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-xs btn-danger" %>
					</div>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path, class: "btn btn-success" %>

app/views/teachers/new.html.erb
<div class="page-header">
	<h1>New teacher</h1>
</div>

<%= render 'form' %>

<%= link_to 'All Teachers', teachers_path, class: "btn btn-default" %>

app/views/teachers/show.html.erb
<div class="page-header">
	<h1><%= @teacher.name %></h1>
</div>

<p>
	<strong>Email:</strong>
	<%= mail_to @teacher.email %>
</p>

<h2>Classes</h2>
<table class="table table-striped">
	<thead>
		<tr>
			<th>Course</th>
			<th>Period</th>
			<th>Actions</th>
		</tr>
	</thead>

	<tbody>
		<% @teacher.classrooms.sort_by(&:period).each do |classroom| %>
			<tr>
				<td><%= link_to classroom.course.name, classroom %></td>
				<td><%= classroom.period %></td>
				<td>
					<div class="btn-group btn-group-xs">
						<%= link_to 'Edit', edit_classroom_path(classroom), class: 'btn btn-default btn-xs' %>
						<%= link_to 'Destroy', classroom, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %>
					</div>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

<div class="btn-group">
	<%= link_to 'Edit', edit_teacher_path(@teacher), class: "btn btn-primary" %>
	<%= link_to 'All Teachers', teachers_path, class: "btn btn-default" %>
</div>