config/routes.rb
Docket::Application.routes.draw do
	get "docket" => "docket#index"

	resources :memberships
	resources :exams
	resources :assignments

	resources :classrooms do
		member do
			get "join"
			get "leave"
		end
	end

	resources :courses
	resources :teachers
	resources :sessions

	resources :users do
		member do
			get "activity"
		end
		collection do
			get "activity" => "users#index_activities"
		end
	end

	resources :events do
		member do
			get "join"
			get "leave"
		end
	end

	get "sessions/new"
	get "log_in" => "sessions#new", :as => "log_in"
	get "log_out" => "sessions#destroy", :as => "log_out"

	root "docket#index"

	# Example of regular route:
	#   get "products/:id" => "catalog#view"

	# Example of named route that can be invoked with purchase_url(id: product.id)
	#   get "products/:id/purchase" => "catalog#purchase", as: :purchase

	# Example resource route (maps HTTP verbs to controller actions automatically):
	#   resources :products

	# Example resource route with options:
	#   resources :products dob
	#     member do
	#       get "short"
	#       post "toggle"
	#     end
	#
	#     collection do
	#       get "sold"
	#     end
	#   end

	# Example resource route with sub-resources:
	#   resources :products do
	#     resources :comments, :sales
	#     resource :seller
	#   end

	# Example resource route with more complex sub-resources:
	#   resources :products do
	#     resources :comments
	#     resources :sales do
	#       get "recent", on: :collection
	#     end
	#   end

	# Example resource route with concerns:
	#   concern :toggleable do
	#     post "toggle"
	#   end
	#   resources :posts, concerns: :toggleable
	#   resources :photos, concerns: :toggleable

	# Example resource route within a namespace:
	#   namespace :admin do
	#     # Directs /admin/products/* to Admin::ProductsController
	#     # (app/controllers/admin/products_controller.rb)
	#     resources :products
	#   end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	load_and_authorize_resource
	before_action :set_course, only: [:show, :edit, :update, :destroy]

	# GET /courses
	# GET /courses.json
	def index
		if params[:q]
			@courses = Course.where("LOWER(name) LIKE LOWER(?)", "%" + params[:q] + "%").sort_by(&:name)
		else
			@courses = Course.all.sort_by(&:name)
		end
		respond_to do |format|
			format.html
			format.json { render json: @courses.map { |c| c.name } }
		end
	end

	# GET /courses/1
	# GET /courses/1.json
	def show
	end

	# GET /courses/new
	def new
		@course = Course.new
	end

	# GET /courses/1/edit
	def edit
	end

	# POST /courses
	# POST /courses.json
	def create
		@course = Course.new(course_params)

		respond_to do |format|
			if @course.save
				format.html { redirect_to @course, notice: "Course was successfully created." }
				format.json { render action: "show", status: :created, location: @course }
			else
				format.html { render action: "new" }
				format.json { render json: @course.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /courses/1
	# PATCH/PUT /courses/1.json
	def update
		respond_to do |format|
			if @course.update(course_params)
				format.html { redirect_to @course, notice: "Course was successfully updated." }
				format.json { head :no_content }
			else
				format.html { render action: "edit" }
				format.json { render json: @course.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /courses/1
	# DELETE /courses/1.json
	def destroy
		@course.destroy
		respond_to do |format|
			format.html { redirect_to courses_url }
			format.json { head :no_content }
		end
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_course
		@course = Course.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def course_params
		params.require(:course).permit(:name, :description, :course_number)
	end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for @course, :html => { :class => "form-horizontal" } do |f| %>
	<% if @course.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

			<ul>
				<% @course.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="form-group">
		<%= f.label :name, :class => "col-sm-4 control-label" %>
		<div class="col-sm-8">
			<%= f.text_field :name, :class => "form-control" %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :course_number, :class => "col-sm-4 control-label" %>
		<div class="col-sm-8">
			<%= f.text_field :course_number, :class => "form-control" %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :description, :class => "col-sm-4 control-label" %>
		<div class="col-sm-8">
			<%= f.text_area :description, :class => "form-control" %>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-offset-4 col-sm-8">
			<%= f.submit class: "btn btn-success" %>
		</div>
	</div>
<% end %>

app/views/courses/edit.html.erb
<div class="page-header">
	<h1>Editing course</h1>
</div>

<%= render 'form' %>

<div class="btn-group">
	<%= link_to 'Show', @course, class: "btn btn-primary" %>
	<%= link_to 'All Courses', courses_path, class: "btn btn-default" %>
</div>

app/views/courses/index.html.erb
<div class="page-header">
	<h1>Listing courses</h1>
</div>

<table class="table table-striped">
	<thead>
		<tr>
			<th>Name</th>
			<th>Course number</th>
			<th>Actions</th>
		</tr>
	</thead>

	<tbody>
		<% @courses.each do |course| %>
			<tr>
				<td><%= link_to course.name, course %></td>
				<td><%= course.course_number %></td>
				<td>
					<div class="btn-group btn-group-xs">
						<%= link_to 'Edit', edit_course_path(course), class: 'btn btn-default btn-xs' %>
						<%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %>
					</div>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

<%= link_to 'New Course', new_course_path, class: "btn btn-success" %>

app/views/courses/new.html.erb
<div class="page-header">
	<h1>New course</h1>
</div>

<%= render 'form' %>

<%= link_to 'All Courses', courses_path, class: "btn btn-default" %>

app/views/courses/show.html.erb
<div class="page-header">
	<h1><%= @course.name %></h1>
</div>

<p>
	<strong>Coursebook number:</strong>
	<%= @course.course_number %>
</p>

<p><%= @course.description %></p>

<h2>Classes</h2>
<table class="table table-striped">
	<thead>
		<tr>
			<th>Teacher</th>
			<th>Period</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<% @course.classrooms.each do |classroom| %>
			<tr>
				<td><%= link_to classroom.teacher.name, classroom.teacher %></td>
				<td><%= classroom.period %></td>
				<td>
					<div class="btn-group btn-group-xs">
						<%= link_to 'Show', classroom, class: 'btn btn-info btn-xs' %>
						<%= link_to 'Edit', edit_classroom_path(classroom), class: 'btn btn-default btn-xs' %>
						<%= link_to 'Destroy', classroom, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %>
					</div>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

<div class="btn-group">
	<%= link_to 'Edit', edit_course_path(@course), class: "btn btn-primary" %>
	<%= link_to 'All Courses', courses_path, class: "btn btn-default" %>
</div>