config/routes.rb
Docket::Application.routes.draw do
	get "docket" => "docket#index"

	resources :memberships
	resources :exams
	resources :assignments

	resources :classrooms do
		member do
			get "join"
			get "leave"
		end
	end

	resources :courses
	resources :teachers
	resources :sessions

	resources :users do
		member do
			get "activity"
		end
		collection do
			get "activity" => "users#index_activities"
		end
	end

	resources :events do
		member do
			get "join"
			get "leave"
		end
	end

	get "sessions/new"
	get "log_in" => "sessions#new", :as => "log_in"
	get "log_out" => "sessions#destroy", :as => "log_out"

	root "docket#index"

	# Example of regular route:
	#   get "products/:id" => "catalog#view"

	# Example of named route that can be invoked with purchase_url(id: product.id)
	#   get "products/:id/purchase" => "catalog#purchase", as: :purchase

	# Example resource route (maps HTTP verbs to controller actions automatically):
	#   resources :products

	# Example resource route with options:
	#   resources :products dob
	#     member do
	#       get "short"
	#       post "toggle"
	#     end
	#
	#     collection do
	#       get "sold"
	#     end
	#   end

	# Example resource route with sub-resources:
	#   resources :products do
	#     resources :comments, :sales
	#     resource :seller
	#   end

	# Example resource route with more complex sub-resources:
	#   resources :products do
	#     resources :comments
	#     resources :sales do
	#       get "recent", on: :collection
	#     end
	#   end

	# Example resource route with concerns:
	#   concern :toggleable do
	#     post "toggle"
	#   end
	#   resources :posts, concerns: :toggleable
	#   resources :photos, concerns: :toggleable

	# Example resource route within a namespace:
	#   namespace :admin do
	#     # Directs /admin/products/* to Admin::ProductsController
	#     # (app/controllers/admin/products_controller.rb)
	#     resources :products
	#   end
end

app/models/exam.rb
class Exam < ActiveRecord::Base
	include PublicActivity::Model
	tracked owner: -> (controller, model) { controller && controller.current_user }
	
	belongs_to :classroom
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
	load_and_authorize_resource
	before_action :set_exam, only: [:show, :edit, :update, :destroy]

	# GET /exams
	# GET /exams.json
	def index
		@exams = Exam.all
	end

	# GET /exams/1
	# GET /exams/1.json
	def show
	end

	# GET /exams/new
	def new
		@exam = Exam.new
		@exam.classroom_id = params[:classroom_id]
	end

	# GET /exams/1/edit
	def edit
	end

	# POST /exams
	# POST /exams.json
	def create
		@exam = Exam.new(exam_params)

		respond_to do |format|
			if @exam.save
				format.html { redirect_to @exam, notice: "Exam was successfully created." }
				format.json { render action: "show", status: :created, location: @exam }
			else
				format.html { render action: "new" }
				format.json { render json: @exam.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /exams/1
	# PATCH/PUT /exams/1.json
	def update
		respond_to do |format|
			if @exam.update(exam_params)
				format.html { redirect_to @exam, notice: "Exam was successfully updated." }
				format.json { head :no_content }
			else
				format.html { render action: "edit" }
				format.json { render json: @exam.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /exams/1
	# DELETE /exams/1.json
	def destroy
		@exam.destroy
		respond_to do |format|
			format.html { redirect_to exams_url }
			format.json { head :no_content }
		end
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_exam
		@exam = Exam.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def exam_params
		params.require(:exam).permit(:name, :description, :date, :classroom_id)
	end
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/_form.html.erb
<%= form_for @exam, :html => { :class => 'form-horizontal' } do |f| %>
	<% if @exam.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@exam.errors.count, "error") %> prohibited this exam from being saved:</h2>

			<ul>
				<% @exam.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="form-group">
		<%= f.label :name, class: "col-sm-4 control-label" %>
		<div class="col-sm-8">
			<%= f.text_field :name, class: "form-control" %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :description, class: "col-sm-4 control-label" %>
		<div class="col-sm-8">
			<%= f.text_area :description, class: "form-control" %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :date, class: "col-sm-4 control-label" %>
		<div class="col-sm-8">
			<%= f.date_select :date, class: "form-control" %>
		</div>
	</div>
	<% if params[:classroom_id] %>
		<%= f.hidden_field :classroom_id, value: params[:classroom_id], class: "form-control" %>
	<% else %>
		<div class="form-group">
			<%= f.label :classroom_id, class: "col-sm-4 control-label" %>
			<div class="col-sm-8">
				<%= f.select :classroom_id, current_user.classes.map { |c| [c.course.name, c.id] } %>
			</div>
		</div>
	<% end %>
	<div class="form-group">
		<div class="col-sm-offset-4 col-sm-8">
			<%= f.submit class: "btn btn-success" %>
		</div>
	</div>
<% end %>

app/views/exams/edit.html.erb
<div class="page-header">
	<h1>Editing exam</h1>
</div>

<%= render 'form' %>

<div class="btn-group">
	<%= link_to 'Show', @exam, class: "btn btn-primary" %>
	<%= link_to 'Back to Class', @exam.classroom, class: "btn btn-default" if @exam.classroom%>
</div>

app/views/exams/index.html.erb
<div class="page-header">
	<h1>Listing exams</h1>
</div>

<table class="table table-striped">
	<thead>
		<tr>
			<th>Name</th>
			<th>Class</th>
			<th>Date</th>
			<th>Actions</th>
		</tr>
	</thead>

	<tbody>
		<% @exams.sort_by(&:date).each do |exam| %>
			<tr>
				<td><%= link_to exam.name, exam %></td>
				<td><%= link_to exam.classroom.name, exam.classroom %></td>
				<td><%= exam.date %></td>
				<td>
					<div class="btn-group btn-group-xs">
						<%= link_to "Edit", edit_exam_path(exam), class: 'btn btn-default btn-xs' %>
						<%= link_to "Destroy", exam, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %>
					</div>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

<%= link_to 'New Exam', new_exam_path, class: "btn btn-primary" %>

app/views/exams/new.html.erb
<div class="page-header">
	<h1>New exam</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back to Class', @exam.classroom, class: "btn btn-default" if @exam.classroom %>

app/views/exams/show.html.erb
<div class="page-header">
	<h1><%= @exam.name %></h1>
</div>

<p>
	<a href="<%= classroom_path(@exam.classroom) %>"><%= @exam.classroom.teacher.name %>'s <%= @exam.classroom.period.ordinalize %> period <%= @exam.classroom.course.name %> class</a> will have an exam on <%= @exam.date %>.
</p>

<p><%= @exam.description %></p>

<div class="btn-group">
	<%= link_to 'Edit', edit_exam_path(@exam), class: "btn btn-primary" %>
	<%= link_to 'Back to Class', @exam.classroom, class: "btn btn-default" %>
</div>